services:
  app:
    container_name: ayomi_app
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_ENV=${APP_ENV:-development}
        - APP_DB=${APP_DB:-mongo}
    ports:
      - ${APP_PORT:-8000}:${APP_PORT:-8000}
    command: "python console.py run"
    environment:
      - MONGO_PORT=${MONGO_PORT:-27017}
      - MONGO_HOST=${MONGO_HOST:-db}
      - MONGO_DB=${MONGO_DB:-ayomi}

      - MONGO_CALCULATIONS_COLLECTION_NAME=${MONGO_CALCULATIONS_COLLECTION_NAME:-calculations}

      - APP_PORT=${APP_PORT:-8000}
      - APP_ENV=${APP_ENV:-development}
      - APP_DB=${APP_DB:-mongo}

      - POSTGRES_DB=${POSTGRES_DB:-dev_db}
      - POSTGRES_USER=${POSTGRES_USER:-dev_user}
      - POSTGRES_PASS=${POSTGRES_PASS:-dev_pass}
      - POSTGRES_HOST=${POSTGRES_HOST:-db-sql}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
    healthcheck:
      test: ["CMD-SHELL", "python console.py check-health"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s
    volumes:
      - ./src:/src
    networks:
      - app

networks:
  app:
    name: ayomi_network
    driver: bridge
