"""empty message

Revision ID: 45faa1fbb26f
Revises:
Create Date: 2025-01-18 17:52:00.468397

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "45faa1fbb26f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calculations",
        sa.Column("calculation_id", sa.UUID(), nullable=False),
        sa.Column("expression", sa.TEXT(), nullable=False),
        sa.Column("result", sa.DECIMAL(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("calculation_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("calculations")
    # ### end Alembic commands ###
